#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"

#rm "$HOME/Scripts" 2>/dev/null
#ln -sf "$PWD/scripts" "$HOME/Scripts"
