#!/usr/bin/perl
use v5.26;

for my $tool (qw(jq tar curl)) {
    system("command -v $tool > /dev/null 2>&1") == 0
        or die "$tool not found\n";
}

sub lookup_file {
    my $os   = lc(`uname -s`);
    my $arch = `uname -m`;
    chomp( $arch, $os );
    # $arch = ($arch eq "x86_64") ? "amd64" : $arch;
    $arch = 'amd64' if ($arch eq 'x86_64');
    my $file = `curl -sSL "https://go.dev/dl/?mode=json" \\
       | jq -r '.[0].files[]
       | select(.os == "$os")
       | select(.kind == "archive")
       | select(.arch == "$arch")
       | .filename'`;
    chomp($file);
    return $file;
}

sub downloads {
    my $downloads = $ENV{DOWNLOADS} || '/tmp';
    my $homedown  = $ENV{HOME} . "/Downloads";
    $downloads = $homedown if -d $homedown;
    return $downloads;
}

my $file = lookup_file();
say "file found: $file";
not $file and die "no file found to fetch";
my $downloads = downloads();
my $path      = $downloads . '/' . $file;
my $dir       = $ENV{HOME} . "/.local";

say "Installing Go into $dir ... ";

`curl -fL "https://go.dev/dl/$file" -o "$path"`;
`mkdir -p "$dir"`;
`rm -rf $dir/go`;
`tar -C "$dir" -xzf "$path"`;

say "Installed.";

# Reference: Rob Muhelstein @https://linktr.ee/rwxrob
