#!/bin/bash

# Neovim config switcher
alias nvim-kick='NVIM_APPNAME=nvim-kick nvim'

nvims() {
  items=("default" "nvim-kick")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config: " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim "$@"
}

bind -x '"\C-a": nvims'
