#!/bin/sh
#shellcheck disable=SC2059

g=
c=
r=

if test -t 1; then
	g="\033[31m"
	c="\033[34m"
	r="\033[0m"
fi

printf "${c}dap${r}  - ${g}delete around current paragraph${r}\n"
printf "${c}dip${r}  - ${g}delete current paragraph${r}\n"
printf "${c}diw${r}  - ${g}delete current word${r}\n"
printf "${c}daw${r}  - ${g}delete around current word${r}\n"
printf "${c}diW${r}  - ${g}delete current larger word (ex: --foo-bar)${r}\n"
printf "${c}daW${r}  - ${g}delete around current larger word${r}\n"
printf "${c}yap${r}  - ${g}yank around current paragraph${r}\n"
printf "${c}yip${r}  - ${g}yank current paragraph${r}\n"
printf "${c}ea ${r}  - ${g}append to current word${r}\n"
printf "${c}cw ${r}  - ${g}change to end of current word${r}\n"
printf "${c}ciw${r}  - ${g}change current word${r}\n"
printf "${c}caw${r}  - ${g}change around current word${r}\n"
printf "${c}dw ${r}  - ${g}delete to beginning of next word${r}\n"
printf "${c}daf${r}  - ${g}delete current function${r}\n"
printf "${c}yaf${r}  - ${g}yank current function${r}\n"
printf "${c}dif${r}  - ${g}delete current inner function${r}\n"
printf "${c}yif${r}  - ${g}yank current inner function${r}\n"
printf "${c}dd${r}   - ${g}delete the current line${r}\n"
printf "${c}gqip${r} - ${g}wrap the current paragraph${r}\n"
printf "${c}gqap${r} - ${g}wrap around the current paragraph${r}\n"
printf "${c}>ip${r}  - ${g}indent the current paragraph${r}\n"
printf "${c}<ip${r}  - ${g}dedent the current paragraph${r}\n"
printf "${c}!ip${r}  - ${g}send the current paragraph to shell command${r}\n"
printf "${c}z=${r}   - ${g}see suggestion of misspelled word${r}\n"
printf "${c}zg${r}   - ${g}add the word under cursor to the dictionary${r}\n"
printf "${c}zw${r}   - ${g}mark the word under cursor as incorrect${r}\n"
printf "${c}C-o${r}   - ${g}built-in for navigating the previous jump list${r}\n"
printf "${c}C-i${r}   - ${g}built-in for navigating the next jump list${r}\n"
