#!/usr/bin/bash

count=1
if test -n "$1"; then
	count="$1"
fi

IFS=$'\n'
html=($(grep -E '<li' ~/.w3m_bookmarks.html | tail -"${count}" | pandoc -f html -t markdown --wrap=none))

for line in "${html[@]}"; do
	line=${line/](/]: <}
	line=${line/%)/>}
	echo "$line"
done
